const  Router = require('express')
const authMiddleware= require('../middleware/auth.middleware')
const fileController= require('../controllers/fileController')

const router = new Router()
console.log('aaaaaaaaaaaaaaaaaa')
router.post('/',authMiddleware, fileController.createDir)
router.post('/upload',authMiddleware, fileController.postFile)
router.post('/avatar',authMiddleware, fileController.postAvatar)
router.get('/', authMiddleware, fileController.getFiles)
router.get('/download', authMiddleware, fileController.downloadFile)
router.get('/search', authMiddleware, fileController.searchFile)
router.delete('/', authMiddleware, fileController.deleteFile)
router.delete('/avatar', authMiddleware, fileController.deleteAvatar)
module.exports= router